# Generated by Django 5.1.4 on 2025-05-18 02:48

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localIP', models.CharField(max_length=20)),
                ('phase', models.CharField(default=game.models.Phase['JOINING'], max_length=20)),
                ('day', models.IntegerField(default=1)),
                ('group_lots', models.CharField(default='', max_length=20)),
                ('deck', models.CharField(default='', max_length=500)),
                ('chooser', models.CharField(default='', max_length=100)),
                ('bidder', models.CharField(default='', max_length=100)),
                ('steps', models.IntegerField(default=0)),
                ('log', models.TextField(default='Match opened.\n')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('money', models.IntegerField(default=40)),
                ('lots', models.CharField(default='', max_length=20)),
                ('current_bid', models.IntegerField()),
                ('grain', models.IntegerField(default=0)),
                ('cloth', models.IntegerField(default=0)),
                ('dye', models.IntegerField(default=0)),
                ('spice', models.IntegerField(default=0)),
                ('furs', models.IntegerField(default=0)),
            ],
        ),
    ]
