# Generated by Django 5.1.4 on 2025-05-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_ready_alter_host_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='money_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='reward_pyramid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='reward_pyramid_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='reward_rank',
            field=models.IntegerField(default=0),
        ),
    ]
