# Generated by Django 5.1.4 on 2025-06-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_money_spent_player_reward_pyramid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ai',
            field=models.CharField(default='', max_length=100),
        ),
    ]
